### ISSUE TITLE
Flight with EKF2, only PX4Flow fused

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#1]
This flight worked pretty well.
Altitude hold OK
Position hold OK, was not rock solid, there was a little bit of drifting around the position.

https://logs.px4.io/plot_app?log=e8e66ccc-8fac-4919-95e5-92749c817107

Very interesting that in the log there are a lot of jumps to X=0,Y=0 position.

**Comment by TSC21** [comment]
I don't actually like those jumps on X. It seems to be some hard resets on X position. Are you sure you have to optical flow module properly aligned? You can also find some some watchdog innovation triggering for Optical flow at 8:12, which also corresponds with the sudden jumps to zero. I don't see a reason why is not actually doing the same for the other position resets. Did you saw this behavior before in previous flights with EKF2? Does this happens also with LPE?

**Comment by TSC21** [comment]
One thing: what's your current value for `EKF2_OF_QMIN`? Weirdly enough this seems to be set to 1 (!!!) by default. This should actually have an higher threshold (like 150). This may actually justify that bad flow values may be feeding into the system, together with some resets on flow, which is not what we want.

**Comment by bto-ealdaz** [comment]
Yes, it's properly aligned, when we test it holding the drone in our hand the local_position topic reports X positive values when moving forward and Y positive values when moving to the left ( consistent with ENU)
You will see in our other flight, that PX4flow does not jump to zero, but we will keep an eye on it.
We did not manage to get a stable enough flight with LPE in position hold, but can try tomorrow again and report.

**Comment by bto-ealdaz** [comment]
I will check tomorrow the value of EKF2_OF_QMIN and report , what is the meaning of this parameter?
