### ISSUE TITLE
Auto Mode - Can QGC be used to create a mission indoors

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#11]
Hello Nuno

Is it possible to use QGC to create a mission indoors, i.e. when not using GPS ?

Reason I'm asking is that all the waypoints created expect lat lon, which obviously we don't have.

**Comment by TSC21** [comment]
> Is it possible to use QGC to create a mission indoors, i.e. when not using GPS ?

No. Or you create a predefined list of offboard setpoints and use a offboard ROS node to do the control or you will have to manually set the waypoint on QGC considering the scale.
