### ISSUE TITLE
Slowing down the drone - An option to avoid crashes?

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#12]
I thought that for testing it would make sense to make the drone move more slowly, so when it looses track or something odd happens it doesn't go so fast against well and gives me more reaction time.

I was thinking of reducing all the max speeds on the drone.
MPC_VEL_VALUE
MPC_XY_CRUISE
MPC_TILT_MAX_AIR ( Reducing  max tilt reduces max speed too I think?)

Also thinking of reducing gain for XY position control, MPC_XY_P so that if is more sluggish too.

Does this make sense?
Or do you have any other better suggestions?

**Comment by TSC21** [comment]
1. `MPC_VEL_MANUAL` only works on manual modes, not in assisted or auto modes.
2. `MPC_XY_CRUISE` yes that's the parameter you want to change for sluggish response.
3. `MPC_TILTMAX_AIR` yes that also helps so you don't get too stiff angle responses during the control, and can help with the oscillations a bit.
4. `MPC_XY_P` reduce it a bit but not too much, or the vehicle won't be able to respond properly to position commands.
