### ISSUE TITLE
Position Hold Slight Shaking

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#13]
Hello Nuno
Just thought I'd send you a video ( not great, I'll try to get a better one ) that shows how in position hold the drone shakes a little 
https://www.dropbox.com/s/6n2ch2k6lbn8fah/PositionHoldSlightShaking.mov?dl=0
What are the parameters we need to change to tune this?

In Altitude Hold or Manual it is super steady, no shacking at all.

**Comment by TSC21** [comment]
Already answered on the previous issue. Is mostly a tuning issue.

**Comment by bto-ealdaz** [comment]
Ah, so we tune this:  MPC_XY_P ?

**Comment by TSC21** [comment]
Yeah I will start with that one.
