### ISSUE TITLE
Navigation tool for 2D flight

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#15]
Hello Nuno
What ROS tool or other would you recommend to do some simple navigation / obstacle avoidance with a drone that flies at constant altitude  (so a 2D tool would be OK too)

We have played with move_base today, but not sure it's a great fit as it forces the drone to fly as a wheeled robot ( i.e. only with forward motion and rotation, no sideways motion) 

Have read about Moveit, but not sure if it's over kill or easy to use? 

Thx

**Comment by TSC21** [comment]
You can try MoveIt! (http://moveit.ros.org/). I adapted it for my MSc thesis project so to be able to control a drone model using RViz and using `cmd_vel` for velocity control. But this was some time ago (almost 4 years) so probably I would have to re-adapt it to the current framework. You have an example of Alessio's work for it: https://github.com/AlessioTonioni/Autonomous-Flight-ROS. You have another good example here: https://github.com/wilselby/ROS_quadrotor_simulator (https://www.wilselby.com/research/ros-integration/3d-mapping-navigation/). In the end this actually interacts with `move_base`.

**Comment by TSC21** [comment]
> Have read about Moveit, but not sure if it's over kill or easy to use?

Read this now xD well MoveIt can be used with and without GUI, so I don't think it is an overkill.

**Comment by bto-ealdaz** [comment]
Thanks Nuno, good info, those are the exact two links we were focusing on, so good to know we had the right info.

Interesting that you where using cmd_vel, did you have to send the commands at a pretty high Hz rate to be able to control the drone accurately. At what rate where you publishing them?

I had imagined that most people would be sending the required trajectory as waypoints ( Mission mode style) as the PX4 firmware has a much faster position control loop and does a very good job of going to waypoints and holding position, so thought that that would give a good result.

In a sense it feels like that by sending cmd_vel MoveIt ends up having to do the position control part of the loop, and I thought it wouldn’t be fast enough to do it properly….

Would be interested to know more about how you managed to make it work.

Eduardo

---

Eduardo Aldaz Carroll
CTO
BeTomorrow UK

E: eduardo.aldaz@betomorrow.com
M: +44 (0) 7543 519191
Skype: e.aldaz-carroll

**Comment by TSC21** [comment]
>Interesting that you where using cmd_vel, did you have to send the commands at a pretty high Hz rate to be able to control the drone accurately. At what rate where you publishing them?
>
> Would be interested to know more about how you managed to make it work.

At that time I didn't even had SITL available for testing. It was all done with `hector_quadrotor`. So the commands were all processed internally in the ROS environment. Since then, I didn't get a chance to get it done for PX4 SITL or even a real vehicle. Maybe I have it now :)

> I had imagined that most people would be sending the required trajectory as waypoints ( Mission mode style) as the PX4 firmware has a much faster position control loop and does a very good job of going to waypoints and holding position, so thought that that would give a good result.

Well you can use the PX4 control loop, but why not having your own control loop sending offboard setpoints? You can send `cmd_vel` at pretty high speeds (or even positions, if you do a position-based control) to MAVROS based on the processed paths coming from the global path planner.

**Comment by bto-ealdaz** [comment]
Yes, using position control is what I meant, i.e. sending off board setpoints  as I thought that it might be easier to implement than using cmd_vel directly. I was thinking of using the processed paths coming the path planner too, so I'll keep working on that.
But I'm curious: could I use cmd_vel even in the case where the PX4 doesn't have a position estimation, i.e. if only the vertical LIDAR was connected to it and I instructed it somehow to do altitude hold control? 
Or would OFFBOARD mode refuse to engage without position?
Thanks

**Comment by TSC21** [comment]
> Or would OFFBOARD mode refuse to engage without position?

You can change to OFFBOARD without position, but you can't actually control the vehicle with position setpoints that way, cause it doesn't actually knows where it is. You can though use offboard control of the attitude that way.

**Comment by TSC21** [comment]
> if only the vertical LIDAR was connected to it and I instructed it somehow to do altitude hold control?

Yeah you can do altitude hold offboard if you actually have the Z estimation (which you have always, even without Lidar, cause you have baro).

**Comment by bto-ealdaz** [comment]
And could I send cmd_vel ? or does it need to know it’s position to estimate the speed it’s travelling at?

Eduardo

---

Eduardo Aldaz Carroll
CTO
BeTomorrow UK

E: eduardo.aldaz@betomorrow.com
M: +44 (0) 7543 519191
Skype: e.aldaz-carroll

**Comment by TSC21** [comment]
Without position you can't properly estimate velocity, even if you integrate the IMU data, but that would accumulate a lot of error with time.

**Comment by TSC21** [comment]
The velocity is relative to the local frame. If you don't have a sensor that gives you the movement of the rigid body in a frame, you can't actually know it's velocity on that frame.
