### ISSUE TITLE
LPE - Altitude Hold, shot up straight

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#16]
Hello Nuno
A bit of a strange one, it has happened twice, this last incident was luckily not catastrophic, but previous one did a lot of damage to drone last week, so keen to understand what happened.

I was doing a simple test flight, only Vertical Lidar. When I engaged vertical hold the drone immediately just shot up at full throttle, luckily got stuck on the ceiling and I managed to recover it.
These are the logs:
https://logs.px4.io/plot_app?log=931d4aad-9f5c-4892-977d-2cce88206e54

The fuse settings are taking only Vision ( there was none provided at the time)
![screen shot 2018-02-02 at 14 01 36](https://user-images.githubusercontent.com/35691522/35736917-aa1c7f60-0821-11e8-837c-c24395c1e276.png)

The version was 1.7.3.dev

Let me know if you need more info to try to understand
Thanks

**Comment by TSC21** [comment]
https://logs.px4.io/plot_app?log=931d4aad-9f5c-4892-977d-2cce88206e54#Nav-Local-Position-Z - somethine terribly wrong happen with the Z estimation - an advice: when you are doing these tests, make sure you have the plot analyser of QGC up and tracking the estimation of `LOCAL_POSITION_NED.x`, `LOCAL_POSITION_NED.y` and `LOCAL_POSITION_NED.z` so you are assured that nothing wrong is going to happen when you change to assisted modes. Did anything happened on the visual estimation that may had lead to this? Cause from my perspective both baro and distance sensor (lidar) readings seem ok.

**Comment by bto-ealdaz** [comment]
Thanks for the info.
In fact we have no visual estimation, no sensors at all, only the Lidar… 

Eduardo

---

Eduardo Aldaz Carroll
CTO
BeTomorrow UK

E: eduardo.aldaz@betomorrow.com
M: +44 (0) 7543 519191
Skype: e.aldaz-carroll
