### ISSUE TITLE
Flight with EKF2 + Flow + Vision 

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#2]
PX4 with version 1.7.3 stable. 

We tested before flight that both vision and local_position topics where giving sensible values. Moved the drone in X,Y,Z axes, all seemed correct.
https://logs.px4.io/plot_app?log=4c2298c8-1cd5-4025-8902-5901a7843685
Started flight
Alt hold worked OK
Pos hold did not work, it would not stay in position at all. 

As drone drifted away I had to switch to Altitude hold again to gain control. Then tried a couple of more times to set in Position hold but it got rejected.

Vision data provided during the flight seemed correct ( we were looking at the data directly on terminal so only an impression) 
local_position/pose clearly was not correct, seemed a large delay between vision data and local_position.

Rosbag here:
https://www.dropbox.com/s/q3bop032tj72y1m/2018-01-22-17-41-16.bag?dl=0

We also run the process_log_data_ekf python script in case it's useful.
https://www.dropbox.com/s/dwhk93evjcvm9wu/log_45_2018-1-22-17-43-18.ulg.pdf?dl=0

The innovations for X,Y pos don't look right ( page 4 )

**Comment by TSC21** [comment]
First observation: https://logs.px4.io/plot_app?log=4c2298c8-1cd5-4025-8902-5901a7843685#Nav-Yaw-Angular-Rate - You need to tune your yaw rate.

**Comment by bto-ealdaz** [comment]
We did notice some weird behaviour of yaw, in fact in one of our last tests the drone kept rotating continuously even though there was no yaw input ( stick at zero )
Is that related to your observation in any way?
How do we tune the yaw rate? I'm not even sure of what it means really... so any links appreciated

**Comment by TSC21** [comment]
Second: it feels like the estimator is taking some delay on setting the position based on the vision feed, which actually results on a delay when triggering the position hold. At what rate are you feeding the ORB-SLAM2 visual odometry?

**Comment by bto-ealdaz** [comment]
We are feeding it at 10Hz

**Comment by TSC21** [comment]
> How do we tune the yaw rate? I'm not even sure of what it means really... so any links appreciated

Try to increase `MC_YAWRATE_P` to 0.22 and `MC_YAWRATE_I` to 0.12.

> Is that related to your observation in any way?

It may be but I don't actually think you have your `EKF2_AID_MASK` set correctly. From my perspective, bit 1, 3 and 4 should be set, meaning 2^1+2^3+2^4=26, right? You have it set to 10.

**Comment by bto-ealdaz** [comment]
On yaw, note than when flying manual yaw control feels very responsive and very well behaved, no oscillations at all when changing yaw. I would have never imagined it needed any tuning, what is it that you've seen we would need to correct? 
Is it that you'd like it to follow the yaw setpoint more closely?

**Comment by TSC21** [comment]
Oh and bit 6 should also be set: `6 : set to true if the EV observations are in a non NED reference frame and need to be rotated before being used`.

**Comment by bto-ealdaz** [comment]
We have only set AID mask to Vision Fusion and Flow Fusion. What are the other bits? ( Don't have the drone with me now)

**Comment by TSC21** [comment]
> I would have never imagined it needed any tuning, what is it that you've seen we would need to correct?
Is it that you'd like it to follow the yaw setpoint more closely?

I am not saying that is the main issue. I am just saying it may be improved.

**Comment by TSC21** [comment]
> We have only set AID mask to Vision Fusion and Flow Fusion. What are the other bits? ( Don't have the drone with me now)

https://dev.px4.io/en/advanced/parameter_reference.html#EKF2_AID_MASK

**Comment by bto-ealdaz** [comment]
EV observations? are these the vision ones? 
But are they not converted into NED format by mavros? We supply them in ENU format to the vision topic, but thought they would be converted?

**Comment by bto-ealdaz** [comment]
We don't use vision yaw as we've had problems with yaw in other tests and thought it was better for the time being to simplify and just trust the magnetometers.

**Comment by TSC21** [comment]
> But are they not converted into NED format by mavros? We supply them in ENU format to the vision topic, but thought they would be converted?

I would recommend try it if you actually don't have success when you activate the vision yaw fusion. Yes MAVROS converts and sends it in the NED frame.

**Comment by bto-ealdaz** [comment]
I guess this links well with our other question ( see issue 3) regarding if we should initialise the drone in a particular heading, as ORB-SLAM sets zero heading to the heading it has when it's started. 
We don't know if we're doing this properly.

**Comment by TSC21** [comment]
> We don't use vision yaw as we've had problems with yaw in other tests and thought it was better for the time being to simplify and just trust the magnetometers.

Hmm ok but you may face some issues when fusing mag data indoors, specially if you are near electronic equipment. I don't see any mag innovations, so I guess that would be good at this point, but seems it is drifting on position and yaw.

**Comment by TSC21** [comment]
Flight check: did you calibrate your sensors before flights? Specially mag?

**Comment by bto-ealdaz** [comment]
We calibrated them, but not before every flight. Should we?

**Comment by bto-ealdaz** [comment]
Sorry Nuno, a bit of newbie question, but what does not seeing mag innovations mean? Is it good or bad? 
Are you referring to something you've seen here?
https://www.dropbox.com/s/dwhk93evjcvm9wu/log_45_2018-1-22-17-43-18.ulg.pdf?dl=0

In that pdf we saw that the innovations of X,Y appeared to be too large? and larger than the red lines that seem to be some sort of limit...

**Comment by TSC21** [comment]
> I guess this links well with our other question ( see issue 3) regarding if we should initialise the drone in a particular heading, as ORB-SLAM sets zero heading to the heading it has when it's started.

If you don't align the vehicles with the magnetic north, and given you are not merging vision yaw, probably that explains why you actually have a misreading on the position estimation, yes. That won't happen if you merge vision yaw.

**Comment by bto-ealdaz** [comment]
OK, i suspected something like that. But we where aligning with East, according to ENU...

**Comment by TSC21** [comment]
> but what does not seeing mag innovations mean?

From the estimation perspective, means good, because it actually is not detecting weird values that would screw the prediction and the correction steps of the EKF.

> In that pdf we saw that the innovations of X,Y appeared to be too large?

If they are large, means that there are some bad readings of X,Y that would basically screw the EKF predictions, and that's why you have fault detection, that pick up these innovation values (based on the computed residuals) and launch the fault detection for the sensors (saying something like vision fault, or baro fault, etc). The functioning of EKF2 is a little bit more complex than LPE (which is also an EKF itself but not a multiplicative one). I'm kinda more comfortable on exploring LPE myself than EKF2 for the reason I told you before: I took part on a little of its development and I already worked with it a lot, by the opposite with EKF2, that Paul wrote and designed.

**Comment by TSC21** [comment]
> OK, i suspected something like that. But we where aligning with East, according to ENU...

I think that doesn't make a difference. You can try align it with North instead and check what you get. I do recommend fusing vision yaw though, cause otherwise you will always have to do these alignments and the vehicle won't ever be aligned with the it's frame of reference.

**Comment by bto-ealdaz** [comment]
OK, will try tomorrow.
Yes, we wanted to do LPE too because you're more familiar with it, it's just that for some reason as I mentioned we haven't had much success with position hold...

**Comment by TSC21** [comment]
> it's just that for some reason as I mentioned we haven't had much success with position hold...

Please send me a log so I can check. LPE does the position estimation while `attitude_estimator_q` does the attitude estimation in that case.

**Comment by bto-ealdaz** [comment]
OK will send you a log tomorrow.
Can you think of a reason why EKF2 version 1.7.3. stable accepts our vision data, but that the latest master doesn't ?
Have they changed or added some sort of vision data quality filter?

**Comment by bto-ealdaz** [comment]
Lastly for today, does this data look OK? 
<img width="774" alt="screen shot 2018-01-22 at 23 16 13" src="https://user-images.githubusercontent.com/35691522/35249549-5515698c-ffca-11e7-9905-be8bf22cf61b.png">

**Comment by TSC21** [comment]
> Anything you can conclude from this?

Not really. What are the red ones supposed to be? The estimated position? But you can see by the blue ones there were some high innovations on position, which may result on fault or bad estimations. (peaks of 2.53m is considered high).

**Comment by bto-ealdaz** [comment]
Ah, I have really no idea what the red lines are, I was hoping you would... I thought it might be related to the Gate parameter, and that anything over the red line would be rejected...
