### ISSUE TITLE
Initial orientation of the drone

### ISSUE THREAD

**Issue by zhukovv** [BeTomorrowUK/Firmware#3]
Since our vision positioning system doesn't know anything about global orientation, we try to orient a drone properly before a flight, to be sure that PX4 receives zero heading at the beginning.

Because with incorrect initial orientation a drone starts to rotate right after takeoff.

In today's tests we faced it to magnetic East, according to ROS ENU, but now we think that maybe we should head it North, according to NED?

**Comment by bto-ealdaz** [comment]
I'm thinking that another way to frame the question is: Do  EKF2 or LPE expect the drone/ or vision data to be oriented in any particular direction before take off?

Currently with ORB-SLAM zero heading for vision is whatever heading the drone has when the algorithm is started.  
How does EKF2 or LPE handle this?

**Comment by TSC21** [comment]
> I'm thinking that another way to frame the question is: Do EKF2 or LPE expect the drone/ or vision data to be oriented in any particular direction before take off?

If you don't fuse vision yaw, then yes.

**Comment by bto-ealdaz** [comment]
And you recommend facing north ( I'm just repeating here for our records)

**Comment by TSC21** [comment]
> And you recommend facing north ( I'm just repeating here for our records)

I recommend fusing vision yaw :)

**Comment by TSC21** [comment]
Any other detail that requires attention here?

**Comment by bto-ealdaz** [comment]
No, I think we're clear.
We're fusing yaw and we're taking off facing east for the moment. Seems to work well.
