### ISSUE TITLE
Improve Radio comms - 

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#5]
When using the radio with QGC loading the data and update rate are very low, need to try to find a solution.

**Comment by TSC21** [comment]
Suggestion: https://pixhawk.org/peripherals/8266

**Comment by bto-ealdaz** [comment]
Thanks! We have these units for all our pixracers, but unfortunately we are using pix hawk2.1, and we don’t think we can use them?

Also our experience with the pixracer is that the connection process ( i.e. the period where the green bar appears on the top ) with these wifi units is still very slow > 30s to a minute … is that not the case for you?

**Comment by bto-ealdaz** [comment]
We have sorted out the issue by removing the ECC in the radio, see here:
http://discuss.px4.io/t/sik-radio-telemetry-very-slow-removing-ecc-made-big-difference/5528

I think the issue is that there is a lot more data been sent in Mavlink than there was the last time i used these radios
