### ISSUE TITLE
Proper TF's and Frame ID's

### ISSUE THREAD

**Issue by zhukovv** [BeTomorrowUK/Firmware#6]
For `/mavros/odomery/odom` we set `frame_id=local_origin` and `child_frame_id=local_origin_ned`, is that correct?

Does EKF or LPE take TF's into account somehow or we shouldn't worry about that?

**Comment by TSC21** [comment]
You should call `frame_id` `fcu` or `vehicle` for example and `child_frame_id` the `local_origin`. They are then used here https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/odom.cpp#L84-L92 to compute the respective transforms in body and world frames from ENU to NED.

> Does EKF or LPE take TF's into account somehow or we shouldn't worry about that?

This is not relevant to that stage but rather to MAVROS that needs to compute the transforms before sending the data to the FCU.
