### ISSUE TITLE
Mavros topic /mavros/setpoint_velocity/cmd_vel_unstamped useable?

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#7]
Hi Nuno
We were wondering if we can use this topic?
topic /mavros/setpoint_velocity/cmd_vel_unstamped
We are interested in using move_base node in ROS and it uses cmd_vel so we were thinking of doing this remapping:

<remap from="cmd_vel" to="/mavros/setpoint_velocity/cmd_vel_unstamped"/>

Will this work?

**Comment by TSC21** [comment]
Yeah I don't see why not. Just make sure about the frame of reference of the velocities you are publishing. If the velocities are in the world frame, you should use the `LOCAL_NED` frame on the `setpoint_velocity` plugin, while if the velocities are in the body frame, you should use the `BODY_NED` frame.

**Comment by bto-ealdaz** [comment]
Good to know
Have you every tried it yourself?

**Comment by TSC21** [comment]
I personally never used `move_base` for this situation.

**Comment by bto-ealdaz** [comment]
Does mavros convert the topic /cmd_vel into Mavlink POSITION_TARGET_LOCAL_NED message?

Does it also set the necessary flags to indicate that only velocities should be taken into account when using cmd_vel? ( i.e. so that the PX4 doesn't also think it's been commanded to go to position 0,0,0 as cmd_vel doesn't send position data and 0 will be the default value )


`type_mask | uint16_t | Bitmask to indicate which dimensions should be ignored by the vehicle: a value of 0b0000000000000000 or 0b0000001000000000 indicates that none of the setpoint dimensions should be ignored. If bit 10 is set the floats afx afy afz should be interpreted as force instead of acceleration. Mapping: bit 1: x, bit 2: y, bit 3: z, bit 4: vx, bit 5: vy, bit 6: vz, bit 7: ax, bit 8: ay, bit 9: az, bit 10: is force setpoint, bit 11: yaw, bit 12: yaw rate`

**Comment by TSC21** [comment]
Yes. You can use `setpoint_velocity` plugin for that. Just don't forget to set if the velocities are in the local (`LOCAL_NED`) or in the body (`BODY_NED`) frames on the `px4_config.yml`. You can also use the `setpoint_raw` plugin but that requires you to set the bitmask flags also, while `setpoint_velocity` handles that automatically.

**Comment by bto-ealdaz** [comment]
So if I use LOCAL_NED I'm using the world frame, but in NED format?
So I need to convert my cmd_vel from ROS which are in ENU to NED then?

**Comment by TSC21** [comment]
No. It's just saying that the data on the Mavlink msg goes in the body or local frame (NED). MAVROS handles the conversion from ENU to NED.

**Comment by bto-ealdaz** [comment]
Ah, OK, understood. Makes sense

**Comment by bto-ealdaz** [comment]
I'm trying to specify with px4_config.yml
But the entry for set point position is empty
```
# setpoint_position
setpoint_position:
  tf:
    listen: false           # enable tf listener (disable topic subscribers)
    frame_id: "map"
    child_frame_id: "target_position"
    rate_limit: 50.0

# setpoint_velocity
# None

# vfr_hud
# None

```

Can you tell me what I need to add to ask for world frame mode?

**Comment by TSC21** [comment]
What MAVROS version are you using? This exists on latest master: https://github.com/mavlink/mavros/blob/master/mavros/launch/px4_config.yaml#L111

**Comment by TSC21** [comment]
This feature exists since release 0.22.

**Comment by bto-ealdaz** [comment]
OK, let me see

**Comment by bto-ealdaz** [comment]
How can i tell? I think this version is probably what was installed with ros

**Comment by bto-ealdaz** [comment]
I mean we installed with sudo apt-get install etc

**Comment by bto-ealdaz** [comment]
OK, removing it and installing it from our fork

**Comment by TSC21** [comment]
0.22 was releases on December 11, so it is already on the deb package list - https://github.com/mavlink/mavros/releases/tag/0.22.0. Can you issue `apt dist-upgrade`?

**Comment by TSC21** [comment]
> OK, removing it and installing it from our fork

Not needed. You probably just have not updated it yet.

**Comment by bto-ealdaz** [comment]
Ah, that is really good that it’s set to the latest.
I have reinstalled with apt-get and I have the right version now I think?

Unpacking ros-kinetic-mavros (0.22.0-0xenial-20180125-133018-0800) ...


Eduardo

---

Eduardo Aldaz Carroll
CTO
BeTomorrow UK

E: eduardo.aldaz@betomorrow.com
M: +44 (0) 7543 519191
Skype: e.aldaz-carroll

**Comment by TSC21** [comment]
Yes that's the latest release.

**Comment by bto-ealdaz** [comment]
Bugger, we've got an issue now with the Transform tree,
I'm not getting the map to base_link tf anymore even if I enable it in the config file like this:
```
# local_position
local_position:
  frame_id: "map"
  tf:
    send: true
    frame_id: "map"
    child_frame_id: "base_link"
    send_fcu: false

```

**Comment by bto-ealdaz** [comment]
I'm running SITL with jmavsim and we're experiencing weird behaviour:
I'm running the default px4_config.yaml , which has LOCAL_NED

If I publish a simple cmd_vel message with positive X,  the drone moves in the negative global frame X direction

` rostopic pub -r 10 /mavros/setpoint_velocity/cmd_vel geometry_msgs/TwistStamped '{twist: {linear: {x: 0.01, y: 0, z: 0}, angular: {x: 0, y: 0, z: 0}}}'`

I publish the command with positive Y, the drone moves in positive X mostly, but also in Y 

` rostopic pub -r 10 /mavros/setpoint_velocity/cmd_vel geometry_msgs/TwistStamped '{twist: {linear: {x: 0, y: 0.01, z: 0}, angular: {x: 0, y: 0, z: 0}}}'`

I can send you some rosbags, this is very confusing...

Any idea of what is going on?

**Comment by bto-ealdaz** [comment]
It almost feels as it's just using BODY_NED

**Comment by bto-ealdaz** [comment]
Damn, what a waste of time, it seems it's an issue with Jmavsim, it works fine with Gazebo

**Comment by TSC21** [comment]
Can you please open an issue on jMAVSim repo so this can be tracked later? Thanks

**Comment by TSC21** [comment]
I think the reason is that jMAVSim environment works on the NED frame and not in the ENU. So probably not an issue at all

**Comment by bto-ealdaz** [comment]
I suspect you're right

**Comment by TSC21** [comment]
Though I feel it weird cause the pose and atittude of the vehicle on the simulator should be a result of the changes on the pose and atittude on the SITL side. If you send the setpoints on NED, then SITL processes those in NED, meaning the position is on the NED frame (while the atittude is on the FRD body frame). So it's the same for Gazebo and jMAVSim, so I don't quite get why jMAVSim processes the pose that way.
