### ISSUE TITLE
Suggestions for Landing in Offboard Mode

### ISSUE THREAD

**Issue by wsolichin-bto** [BeTomorrowUK/Firmware#8]
When the drone is taking off in offboard mode, what is the suggested command to land it safely in offboard mode?

Thanks.

**Comment by bto-ealdaz** [comment]
Is it as simple as sending a set local position  a small negative altitude? Assuming there is no drift or error in altitude position? 

Thanks

**Comment by TSC21** [comment]
> Is it as simple as sending a set local position a small negative altitude? Assuming there is no drift or error in altitude position?

It is actually recommended that you switch to `LAND` mode instead of using altitude offsets, cause the `LAND` mode is actually ready for detecting the landing state.
