### ISSUE TITLE
LPE - Vision + Optical Flow - Successful Position Hold until crash

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#9]
Today we tested LPE as we would prefer to use it given that you're more familiar with it.
Before flying we enabled LPE and tested holding the drone that the local_position was well behaved by comparing it to vision while moving the drone in N-S and E-W directions.

We then flew position hold, which was pretty good, although the drone sort of flutters in position, it's not as steady as with EKF2, so I think we need to tune something. However it turned out to be unreliable it would suddenly start to drift
https://logs.px4.io/plot_app?log=5ad83929-ec9a-43b7-b558-9e687e247d23

When position hold lost it and the drone started to drift I would switch to altitude hold, you can see the transitions in the Flight Review.

But mostly we think that Optical Flow is not working well enough to keep the drone stable in position, in fact we run a test with only optical flow Fusion (and Lidar) and position hold without vision was very unreliable... 

Any thoughts on what we can do to improve it?

**Comment by bto-ealdaz** [comment]
Also what happens when Quality of OF is below the QMIN of 150, what does the estimator use for position? Just vision?

We had pretty good quality all during the flight, except at the end and I think it's when we had the issue

<img width="955" alt="screen shot 2018-01-25 at 22 09 14" src="https://user-images.githubusercontent.com/35691522/35415151-7dee09b4-021c-11e8-87ad-5b48ce3e46aa.png">

**Comment by bto-ealdaz** [comment]
This shows when vision and local position didn't agree anymore. 
3.- Anyway we can get the system to trust vision more than Optical Flow?

<img width="974" alt="screen shot 2018-01-25 at 22 17 51" src="https://user-images.githubusercontent.com/35691522/35415473-a9a7c580-021d-11e8-8a04-5db47f19c4d7.png">

**Comment by TSC21** [comment]
> 1.- Also what happens when Quality of OF is below the QMIN of 150, what does the estimator use for position? Just vision?

It triggers sensor fault for flow and continues fusing the other data that it has available till it gets good quality on flow again to fuse it back again.

> 2.- Should we increase the value of QMIN ? It seems that with values under 230 we have issues

I would likely think that is impossible. Quality values above 200 is enough to have good flow estimations. Unless something is wrong on the Flow driver.

> 3.- Anyway we can get the system to trust vision more than Optical Flow?

Yes. You can increase the `LPE_FLW_QMIN` for flow and decrease the std deviation (`LPE_VIS_XY` and `LPE_VIS_Z`) for vision.
